# -*- coding: utf-8 -*-
"""BOW-Praktek1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B4UM0MOdrVfB4KMKIQ7FtlXVsvQYcQTD

Praktek BOW
=============================

***Universitas Dian Nuswantoro***

Praktek BOW

***Febilah Purtin / A11.2022.14209***
=============================
***Universitas Dian Nuswantoro***
"""

import pandas as pd
import numpy as np

dataset = pd.read_csv('clean_dataset_stem.csv',sep=';')

dataset.shape

dataset.head(10)

dataset_feature = dataset['ProcessedText'].astype(str)

dataset_label = dataset['Sentimen']

dataset_feature

dataset_label

"""# cek distribusi label"""

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

# Visualizing the target variable
plt.figure(figsize=(12,8))
sns.distplot(dataset_label, label=f'target, skew: {dataset_label.skew():.2f}')
plt.legend(loc='best')
plt.show()

dataset_label.value_counts()

"""# BOW"""

from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()

X = vectorizer.fit_transform(dataset_feature)

vectorizer.get_feature_names_out()

print(X.toarray())

vectorizer2 = CountVectorizer(analyzer='word', ngram_range=(2, 2))

X2 = vectorizer2.fit_transform(dataset_feature)

print(X2.toarray())

"""### Simulasi Corpus"""

corpus = [
    'This is the first Document.',
    'This document is the second document.',
    'And this is the third one.',
    'Is this the first document?',
]

vectorizer = CountVectorizer()

Z = vectorizer.fit_transform(corpus)

vectorizer.get_feature_names_out()

print(Z.toarray())

vectorizer2 = CountVectorizer(analyzer='word', ngram_range=(2, 2))

Z2 = vectorizer2.fit_transform(corpus)

vectorizer2.get_feature_names_out()

print(Z2.toarray())