# -*- coding: utf-8 -*-
"""BOW-Praktek1-checkpoint.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pz_JEHXPqkGlcypC6N_K5GFEJRsfrb8f

Praktek BOW
=============================

**Modul untuk Pembelajaran Analitika Media Sosial**

**Author:** *Dr. Eng. Farrikh Alzami, M.Kom*, *Abu Salam, M.Kom*

Program Studi Sistem Informasi S1

***Universitas Dian Nuswantoro***
"""

import pandas as pd
import numpy as np

dataset = pd.read_csv('clean_dataset_stem.csv',sep=';')

dataset.shape

dataset_feature = dataset['ProcessedText'].astype(str)

dataset_label = dataset['Sentimen']

"""# cek distribusi label"""

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

# Visualizing the target variable
plt.figure(figsize=(12,8))
sns.distplot(dataset_label, label=f'target, skew: {dataset_label.skew():.2f}')
plt.legend(loc='best')
plt.show()

dataset_label.value_counts()

"""# BOW"""

from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()

X = vectorizer.fit_transform(dataset_feature)

X

print(vectorizer.get_feature_names_out())

print(X.toarray())

vectorizer2 = CountVectorizer(analyzer='word', ngram_range=(2, 2))

X2 = vectorizer2.fit_transform(dataset_feature)

print(vectorizer2.get_feature_names_out())

print(X2.toarray())

print(X2)

