# -*- coding: utf-8 -*-
"""textProcessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12aQ8wsECNqCv_4ao8vpjOEq7AO_aUspp

Analitika Media Sosial
==============
***Febilah Purtin / A11.2022.14209***
=============================
***Petunjuk Menggunakan Reguler Expresion***

***Universitas Dian Nuswantoro 2022***

---

### Mengenal String dalam Python
Sebelum menggunakan library untuk text pre procesing, lebih baik jika mengenal type string dalam python.
"""

word = 'Analitika Media Sosial'
print(len(word))

multiline = '''1
2
3
'''
print(len(multiline))

str1 = '1'
str2 = '2'

print(str1 + str2)

ch1 = 'a'
ch2 = ' ' #space
ch3 = 'A'

print(ord(ch1))
print(ord(ch2))
print(ord(ch3))

print(chr(65))

cthString="Analitika Media Sosial"
vokal = ['a','i','u','e','o']

for i in range(len(cthString)):
    if cthString[i].lower() in vokal:
        continue
    print(cthString[i], end="")

cthSlice = "Analitika Media Sosial"

print(cthSlice[1::4])
print(cthSlice[1:5])
print(cthSlice[3:])
print(cthSlice[:3])
print(cthSlice[::2])

alphabet = 'abcdefghijklmnopqrstuvwxyz'

print(alphabet[1])
del alphabet[0]

alphabet.insert("A")

print(min("aAbByYzZ"))

t = "theta"
print(t.find('ta'))

txt = """A variation of the ordinary lorem ipsum
text has been used in typesetting since the 1960s
or earlier, when it was popularized by advertisements
for Letraset transfer sheets. It was introduced to
the Information Age in the mid-1980s by the Aldus Corporation,
which employed it in graphics and word-processing templates
for its desktop publishing program PageMaker (from Wikipedia)"""

fnd = txt.find('the')
while fnd != -1:
    print(fnd)
    fnd = txt.find('the', fnd + 1)

"""#### 1. Some of the methods offered by strings are:

- `capitalize()` – changes all string letters to capitals;
- `center()` – centers the string inside the field of a known length;
- `count()` – counts the occurrences of a given character;
- `join()` – joins all items of a tuple/list into one string;
- `lower()` – converts all the string's letters into lower-case letters;
- `lstrip()` – removes the white characters from the beginning of the string;
- `replace()` – replaces a given substring with another;
- `rfind()` – finds a substring starting from the end of the string;
- `rstrip()` – removes the trailing white spaces from the end of the string;
- `split()` – splits the string into a substring using a given delimiter;
- `strip()` – removes the leading and trailing white spaces;
- `swapcase()` – swaps the letters' cases (lower to upper and vice versa)
- `title()` – makes the first letter in each word upper-case;
- `upper()` – converts all the string's letter into upper-case letters.

#### 2. String content can be determined using the following methods (all of them return Boolean values):

- `endswith()` – does the string end with a given substring?
- `isalnum()` – does the string consist only of letters and digits?
- `isalpha()` – does the string consist only of letters?
- `islower()` – does the string consists only of lower-case letters?
- `isspace()` – does the string consists only of white spaces?
- `isupper()` – does the string consists only of upper-case letters?
- `startswith()` – does the string begin with a given substring?

# Table of contents
- [Cleaning Words](#cleaning-words)
    - [import library](#import-library)
    - [remove tab new line and back slice](#remove-tab-new-line-and-back-slice)
    - [remove non ASCII emoticon chinese word](#remove-non-ASCII-emoticon-chinese-word)
    - [remove mention link hashtag](#remove-mention-link-hashtag)
    - [remove RT](#remove-rt)
    - [lower](#lower)
    - [remove incomplete url](#remove-incomplete-url)
    - [remove number](#remove-number)
    - [remove whitespace leading and trailing](#remove-whitespace-leading-and-trailing)
    - [remove multiple whitespace into single whitespace](#remove-multiple-whitespace-into-single-whitespace)
    - [remove single char](#remove-single-char)
    - [remove excessive dot](#remove-excessive-dot)
    - [remove punctuation](#remove-punctuation)
    - [remove excessive whitespace](#remove-excessive-whitespace)

# Cleaning Words <a name="cleaning-words"></a>

asumsikan kita sudah mendapat data dari twitter, kemudian kita ingin membersihkan datanya. Maka, kita bisa menggunakan `regular expression`

sebagai contoh:

`RT : @alzami1986 suka menonton Attack on Titans! (進撃の巨人) #aot  setiap kamis pukul 21.00 di http://netflix.com/aot . \\n meski tidak suka kekerasan, tapi cukup menikmati ?! #EldiaHarusMenang melawan #Marley  A ... `
"""

text = 'RT : @alzami1986 suka menonton Attack on Titans! (進撃の巨人) #aot  setiap kamis pukul 21.00 di http://netflix.com/aot . \\n meski tidak suka kekerasan, tapi cukup menikmati ?! #EldiaHarusMenang melawan #Marley  A ...'

print(text)

"""## import library <a name="import-library"></a>"""

import re
import string
import time
from copy import deepcopy

"""## remove tab new line and back slice  <a name="remove-tab-new-line-and-back-slice"></a>"""

hasil = text.replace('\\t'," ").replace('\\n'," ").replace('\\u'," ").replace('\\',"")

hasil

"""## remove non ASCII emoticon chinese word <a name="remove-non-ASCII-emoticon-chinese-word"></a>"""

hasil = hasil.encode('ascii', 'replace').decode('ascii')

hasil

"""## remove mention, link, hashtag <a name="remove-mention-link-hashtag"></a>"""

hasil = ' '.join(re.sub("([@#][A-Za-z0-9]+)|(\w+:\/\/\S+)"," ", hasil).split())

hasil

"""## remove RT <a name="remove-rt"></a>"""

hasil = hasil.replace('RT : ',"")

hasil

"""## lower <a name="lower"></a>"""

hasil = hasil.lower()

hasil

"""## remove incomplete URL <a name="remove-incomplete-url"></a>"""

hasil = hasil.replace('http://',"").replace('https://',"")

hasil

"""## remove number <a name="remove-number"></a>"""

def remove_number(hasil):
    return re.sub(r"\d+", "", hasil)

hasil = remove_number(hasil)

hasil

"""## remove whitespace leading and trailing <a name="remove-whitespace-leading-and-trailing"></a>

digunakan untuk menghapus tanda spasi setelah titik pada akhir kalimat
"""

def remove_whitespace(hasil):
    return hasil.strip()

hasil = remove_whitespace(hasil)

text

hasil

"""## remove multiple whitespace into single whitespace <a name="remove-multiple-whitespace-into-single-whitespace"></a>"""

def remove_whitespace_multi(hasil):
    return re.sub('\s+',' ',hasil)

hasil = remove_whitespace_multi(hasil)

hasil

"""## remove single char <a name="remove-single-char"></a>"""

def remove_single_char(hasil):
    return re.sub(r"\b[a-zA-Z]\b", "", hasil)

hasil = remove_single_char(hasil)

hasil

"""## remove excessive dot <a name="remove-excessive-dot"></a>"""

def remove_excessive_dot(hasil):
    return hasil.replace('...'," ")

hasil = remove_excessive_dot(hasil)

hasil

"""## remove punctuation <a name="remove-punctuation"></a>"""

def remove_punctuation(hasil):
    return hasil.translate(str.maketrans("","",string.punctuation))

hasil = remove_punctuation(hasil)

text

hasil

"""## remove excessive whitespace <a name="remove-excessive-whitespace"></a>"""

document = " saya                    tidak suka sambal     bikin sakit    "

nowhite = ' '.join(document.split())

nowhite