# -*- coding: utf-8 -*-
"""BOW-Praktek2-tfidf.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qy6glXJpc0qTuqIBwuOf5eKIye0Yx60z

Praktek TF-IDF
=============================
***Febilah Putin / A11.2022.14209***

***Universitas Dian Nuswantoro***
"""

import pandas as pd
import numpy as np

dataset = pd.read_csv('clean_dataset_stem.csv',sep=';')

dataset_feature = dataset['ProcessedText'].astype(str)

dataset_feature

dataset.shape

dataset

dataset_label = dataset['Sentimen']
dataset_label

"""# cek distribusi label"""

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

# Visualizing the target variable
plt.figure(figsize=(12,8))
sns.distplot(dataset_label, label=f'target, skew: {dataset_label.skew():.2f}')
plt.legend(loc='best')
plt.show()

dataset_label.value_counts()

"""# TF-IDF"""

from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()

X = vectorizer.fit_transform(dataset_feature)

print(X.shape)

features = vectorizer.get_feature_names_out()

features

idfValues = vectorizer.idf_

d = dict(zip(features, 9 - idfValues))

sortedDict = sorted(d.items(), key = lambda d: d[1], reverse = True)

for i in range(3867):
    print(sortedDict[i])

from wordcloud import WordCloud
import matplotlib.pyplot as plot

def PlotWordCloud(frequency):
    worcloudPlot = WordCloud(background_color="white", width=1500, height=1000)
    worcloudPlot.generate_from_frequencies(frequencies=frequency)
    plot.figure(figsize=(15,10))
    plot.imshow(worcloudPlot, interpolation="bilinear")
    plot.axis("off")
    plot.show()

PlotWordCloud(d)

