# -*- coding: utf-8 -*-
"""PreprocessingEksprasis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10snq8DEpbs_2iSxv836BXEfxS_whWwaK

***Febilah Putin / A11.2022.14209***

***Universitas Dian Nuswantoro***
## ekphrasis Reguler Expression

menggunakan pembersihan kata dengan modul `Eksprasis`

detail lengkap ada disini: https://github.com/cbaziotis/ekphrasis

## install library ekphrasis
"""

!pip install ekphrasis

from ekphrasis.classes.preprocessor import TextPreProcessor
from ekphrasis.classes.tokenizer import SocialTokenizer
from ekphrasis.dicts.emoticons import emoticons

text_processor = TextPreProcessor(
    # terms that will be normalized
    normalize=['email', 'percent', 'money', 'phone', 'user',
        'time', 'date', 'number'],
    # terms that will be annotated
    #annotate={"hashtag", "allcaps", "elongated", "repeated",'emphasis', 'censored'},
    annotate={"hashtag","allcaps","elongated","repeated",'emphasis','censored'},
    fix_html=True,  # fix HTML tokens

    # corpus from which the word statistics are going to be used
    # for word segmentation
    segmenter="twitter",

    # corpus from which the word statistics are going to be used
    # for spell correction
    corrector="twitter",

    unpack_hashtags=True,  # perform word segmentation on hashtags
    unpack_contractions=True,  # Unpack contractions (can't -> can not)
    spell_correct_elong=False,  # spell correction for elongated words

    # select a tokenizer. You can use SocialTokenizer, or pass your own
    # the tokenizer, should take as input a string and return a list of tokens
    tokenizer=SocialTokenizer(lowercase=True).tokenize,

    # list of dictionaries, for replacing tokens extracted from the text,
    # with other expressions. You can pass more than one dictionaries.
    dicts=[emoticons]
)

def bersih_eks(kata):
  return " ".join(text_processor.pre_process_doc(kata))

kalimat = "@alzami1986 berkata bahwa email agus@gmail.com bukan emailnya, 100% yakin bukan emailnya, nomor 08564111111 juga bukan nomor hp nya maka jika ada yang meminta uang $100 atau Rp. 1.000.000 yang harus dikirim tanggal 06-10-2022 pukul 10:30 harap jangan diikuti. silakan hubungi 110. karena mereka adalah PENIPUUUUUU yang suka makan-makan 'uang tidak halal' !!! dan termasuk dalam golongan >:) #scam #penipu"

hasil01 = bersih_eks(kalimat)

print(hasil01)

kalimat2 = 'peeeeniiiiippuuuuuu'
hasil02 = bersih_eks(kalimat2)
print(hasil02)