# -*- coding: utf-8 -*-
"""stemming_sastrawi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HkazzBx5jYWsBWIViQWEGSiZhR9uLwP2

Stemming menggunakan Sastrawi
=============================
***Febilah Putin / A11.2022.14209***

***Universitas Dian Nuswantoro***

# load dataset
"""

import pandas as pd

dataset = pd.read_csv('clean_dataset.csv', sep=';')

dataset.head()

"""# load sastrawi sebagai stemmer"""

from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
factory = StemmerFactory()
stemmer = factory.create_stemmer()

"""## hapus stop words"""

from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory, StopWordRemover, ArrayDictionary

factory = StopWordRemoverFactory()

more_stopword = ['sih', 'nya','rt','loh','lah', 'dd', 'mah', 'nye', 'eh', 'ehh', 'ah', 'yang','yg']

# Tambahkan Stopword Baru
data = factory.get_stop_words()+more_stopword

stopwords_sastrawi = factory.create_stop_word_remover()

dictionary = ArrayDictionary(data)
str_stopwords = StopWordRemover(dictionary)

dataset['finalText_str'] = dataset['step02'].apply(str)

i=0
final_string = []
s = ""
for sentence in dataset["finalText_str"].values:
    filteredSentence = []
    EachReviewText = ""
    st = str_stopwords.remove(sentence)
    s = (stemmer.stem(st))
    filteredSentence.append(s)

    EachReviewText = ' '.join(filteredSentence)
    final_string.append(EachReviewText)

dataset.loc[:, ('ProcessedText')] = final_string

dataset

dataset.to_csv('clean_dataset_stem.csv',sep=';')